```{r setup}
#| message: false
#| include: false
library(tidyverse)
```

# Landscape {.unnumbered}

We developed a [snakemake](https://snakemake.readthedocs.io/en/stable/) and [conda](https://anaconda.org/anaconda/conda) python workflow for automatic climate data gathering from global databases relying here on [TMF](https://forobs.jrc.ec.europa.eu/TMF). The code is available here: <https://github.com/Bioforest-project/LoggingDiversity/tree/main/data> . Figures below show the resulting forest cover around Paracou and orresponding forest cover images through time. Other landscape indices could be derived from TMF data.

```{r prep}
#| eval: false
list.files("data/landscape/", full.names = TRUE) %>% 
  read_tsv() %>% 
  group_by(site, year, forest) %>% 
  summarise(n = n()) %>% 
  group_by(site, year) %>% 
  mutate(n_tot = sum(n)) %>% 
  filter(forest == 1) %>% 
  summarise(intact = n/n_tot*100) %>% 
  write_tsv("outputs/landscape.tsv") 
```

```{r allplot}
#| message: false
#| warning: false
#| fig-cap: "Paracou forest cover through time."
read_tsv("outputs/landscape.tsv") %>% 
  ggplot(aes(year, intact, col = site)) +
  geom_line() +
  theme_bw() +
  xlab("") +
  ylab("Percentage of forest in a radius of 1-km")
```

```{r betterplot}
#| message: false
#| warning: false
#| fig-cap: "Paracou forest cover through time."
read_tsv("data/landscape/paracou_landscape.tsv") %>% 
  ggplot(aes(lon, lat, fill = as.factor(forest))) +
  geom_raster() +
  facet_wrap(~ year) +
  theme_bw() +
  coord_equal() +
  scale_fill_manual(guide = "none", values = c("black", "darkgreen")) +
  theme(axis.text = element_blank(),
        axis.title = element_blank(),
        axis.ticks = element_blank(),
        panel.spacing = unit(0,'lines')) +
  ggtitle("Paracou forest landscape")
```
