```{r setup}
#| message: false
#| include: false
library(tidyverse)
```

# Species {.unnumbered}

This chapter details species diversity metrics.

```{r diversity}
#| eval: false
read_tsv("outputs/gathered.tsv") %>% 
  group_by(site, rel_year, plot, area, delta_ba, diameter_class) %>% 
  summarise(richness = n(),
            shannon = vegan::diversity(abundance, index = "shannon"),
            simpson = vegan::diversity(abundance, index = "simpson")) %>% 
  gather(metric, value, -site, -rel_year, -plot, -area, -delta_ba, -diameter_class) %>% 
  write_tsv("outputs/neutral_metrics.tsv")
```

## Richness

Absolute richness can't be compared among sites as the plot area differs.

> The relation between plot area and richness not being linear, standardising it can be a bit tricky. We could explore the link between site, plot area, and prelogging diversity for that.

```{r richabs}
#| message: false
#| warning: false
#| fig-cap: "Caption."
read_tsv("outputs/neutral_metrics.tsv") %>% 
  filter(metric == "richness") %>% 
  group_by(site, rel_year, plot, delta_ba) %>% 
  summarise(richness = sum(value)) %>% 
  mutate(site = recode(site,
                       "Misiones" = "Missiones (1-ha)",
                       "Paracou" = "Paracou (6.25-ha)")) %>% 
  ggplot(aes(rel_year, richness, col = delta_ba)) +
  geom_line(aes(group = paste(site, plot))) +
  geom_point() +
  theme_bw() +
  scale_color_viridis_c(expression(Delta[BA])) +
  xlab("") + 
  ylab(expression(Rrichness)) +
  geom_vline(xintercept = 0, linetype = "dashed") +
  ggtitle("Absolute") +
  facet_wrap(~ site, scales = "free")
```

```{r richrel}
#| message: false
#| warning: false
#| fig-cap: "Caption."
read_tsv("outputs/neutral_metrics.tsv") %>% 
  filter(metric == "richness") %>% 
  group_by(site, rel_year, plot, delta_ba) %>% 
  summarise(richness = sum(value)) %>% 
  group_by(site, plot, delta_ba) %>% 
  mutate(richness_pre = mean(ifelse(rel_year < 1, richness, NA), na.rm = T)) %>% 
  mutate(rel_richness = (richness-richness_pre)/richness_pre*100) %>% 
  ggplot(aes(rel_year, rel_richness, col = delta_ba)) +
  geom_line(aes(group = paste(site, plot))) +
  geom_point() +
  theme_bw() +
  scale_color_viridis_c(expression(Delta[BA])) +
  xlab("") + 
  ylab(expression(Delta[richness])) +
  geom_vline(xintercept = 0, linetype = "dashed") +
  geom_vline(xintercept = 15, linetype = "dashed", col = "red") +
  ggtitle("Relative to predisturbance")
```

```{r richrelsite}
#| message: false
#| warning: false
#| fig-cap: "Caption."
read_tsv("outputs/neutral_metrics.tsv") %>% 
  filter(metric == "richness") %>% 
  group_by(site, rel_year, plot, delta_ba) %>% 
  summarise(richness = sum(value)) %>% 
  group_by(site, plot, delta_ba) %>% 
  mutate(richness_pre = mean(ifelse(rel_year < 1, richness, NA), na.rm = T)) %>% 
  mutate(rel_richness = (richness-richness_pre)/richness_pre*100) %>% 
  ggplot(aes(rel_year, rel_richness, col = delta_ba)) +
  geom_line(aes(group = paste(site, plot))) +
  geom_point() +
  theme_bw() +
  scale_color_viridis_c(expression(Delta[BA])) +
  xlab("") + 
  ylab(expression(Delta[richness])) +
  geom_vline(xintercept = 0, linetype = "dashed") +
  geom_vline(xintercept = 15, linetype = "dashed", col = "red") +
  ggtitle("Relative to predisturbance") +
  facet_wrap(~ site)
```

```{r richrelpar}
#| message: false
#| warning: false
#| fig-cap: "Caption."
read_tsv("outputs/neutral_metrics.tsv") %>% 
  filter(metric == "richness") %>% 
  group_by(site, rel_year, plot, delta_ba) %>% 
  summarise(richness = sum(value)) %>% 
  group_by(site, plot, delta_ba) %>% 
  mutate(richness_pre = mean(ifelse(rel_year < 1, richness, NA), na.rm = T)) %>% 
  mutate(rel_richness = (richness-richness_pre)/richness_pre*100) %>% 
  filter(site == "Paracou") %>% 
  ggplot(aes(rel_year, rel_richness, col = delta_ba)) +
  geom_line(aes(group = paste(site, plot))) +
  geom_point() +
  theme_bw() +
  scale_color_viridis_c(expression(Delta[BA])) +
  xlab("") + 
  ylab(expression(Delta[richness])) +
  geom_vline(xintercept = 0, linetype = "dashed") +
  geom_vline(xintercept = 15, linetype = "dashed", col = "red") +
  ggtitle("Relative to predisturbance") +
  facet_wrap(~ site) +
  geom_smooth(method = "lm", formula = y ~ poly(x, 4), se = FALSE, aes(group = paste(site, plot)))
```

```{r rich20}
#| message: false
#| warning: false
#| fig-cap: "Caption."
read_tsv("outputs/neutral_metrics.tsv") %>% 
  filter(metric == "richness") %>% 
  group_by(site, rel_year, plot, delta_ba) %>% 
  summarise(richness = sum(value)) %>% 
  group_by(site, plot, delta_ba) %>% 
  mutate(richness_pre = mean(ifelse(rel_year < 1, richness, NA), na.rm = T)) %>% 
  mutate(rel_richness = (richness-richness_pre)/richness_pre*100) %>% 
  filter(rel_year %in% 20:21) %>% 
  ggplot(aes(delta_ba, rel_richness, col = site)) +
  geom_point() +
  geom_smooth(method = "lm", formula = y ~poly(x, 2), se = FALSE) +
  ggtitle("20 years after logging") +
  xlab(expression(Delta[BA])) +
  ylab(expression(Delta[richness]))
```

## Shannon

## Simpson
