```{r set}
#| message: false
#| include: false
library(tidyverse)
library(cmdstanr)
library(bayesplot)
```

# Joint Species 0 {.unnumbered}

```{r fit}
#| eval: false
recovery <- cmdstan_model("models/recovery.stan")
data <- read_tsv("../modelling/data/derived_data/data_rec.tsv", col_types = cols()) %>%
    select(-y) %>% 
    filter(variable %in% c("ba", "diversity_q0_sp")) %>%
    select(-sitenum, -plotnum) %>% 
    pivot_wider(names_from = variable, values_from = value) %>% 
    na.omit() %>% 
    filter(!(site %in% c("Manare", "Montagne Tortue", "Nelliyampathy",
                         "Uppangala", "BAFOG", "Sao Nicolau",
                         "Kabo", "Mil", "Corinto",
                         "Peixoto", "Iwokrama", "Antimary", "Peteco"))) %>% 
    mutate(sitenum = as.numeric(as.factor(site))) %>% 
    mutate(plotnum = as.numeric(as.factor(paste(site, plot)))) %>% 
    arrange(sitenum, plotnum, rel_year)
ind <- data %>%
    select(site, plot, sitenum, plotnum) %>%
    unique()
ba_priors <- read_tsv(file.path("..", "modelling",
                                "chains", paste0("equ_", "ba"), "mu.tsv")) %>% 
    select(-sitenum) %>% 
    left_join(select(ind, site, sitenum) %>% unique()) %>% 
    na.omit()
div_priors <- read_tsv(file.path("..", "modelling",
                                 "chains", paste0("equ_", "diversity_q0_sp"),
                                 "mu.tsv")) %>% 
    select(-sitenum) %>% 
    left_join(select(ind, site, sitenum) %>% unique()) %>% 
    na.omit()
mdata <- list(
    n = nrow(data),
    s = max(data$sitenum),
    p = max(data$plotnum),
    ba = data$ba,
    y = data$diversity_q0_sp,
    t = data$rel_year - 3,
    site = data$sitenum,
    plot = data$plotnum,
    site_plot = ind$sitenum,
    mu_ba_theta_s = ba_priors$median,
    sigma_ba_theta_s = ba_priors$sd,
    mu_theta_s = div_priors$median,
    sigma_theta_s = div_priors$sd
)
fit <- recovery$sample(
    mdata,
    chains = 4,
    parallel_chains = 4,
    save_warmup = FALSE,
    refresh = 100,
    output_dir = "chains/jointsp0/"
)
```

## Fit

```{r fitres}
#| message: false
#| warning: false
fit <- as_cmdstan_fit(list.files("chains/jointsp0/", full.names = TRUE))
data <- read_tsv("../modelling/data/derived_data/data_rec.tsv", col_types = cols()) %>%
  select(-y) %>% 
  filter(variable %in% c("ba", "diversity_q0_gen")) %>%
  select(-sitenum, -plotnum) %>% 
  pivot_wider(names_from = variable, values_from = value) %>% 
  na.omit() %>% 
filter(!(site %in% c("Manare", "Montagne Tortue", "Nelliyampathy",
                         "Uppangala", "BAFOG", "Sao Nicolau",
                         "Kabo", "Mil", "Corinto",
                         "Peixoto", "Iwokrama", "Antimary", "Peteco"))) %>% 
  mutate(sitenum = as.numeric(as.factor(site))) %>% 
  mutate(plotnum = as.numeric(as.factor(paste(site, plot)))) %>% 
  arrange(sitenum, plotnum, rel_year)  %>% 
  gather(variable, y, -plot, -year, -site, -treatment, -harvest_year,
         -longitude, -harvest_year_min, -rel_year, -sitenum, -plotnum)
ind <- data %>%
    select(site, plot, sitenum, plotnum) %>%
    unique()
trajs <- fit$summary(c("y_pred", "ba_pred"), "median") %>% 
  separate(variable,
      c("variable", "pred", "rel_year", "plotnum"),
      convert = TRUE
  ) %>%
  select(-pred) %>% 
  mutate(variable = recode(variable, "y" = "diversity_q0_sp")) %>% 
  rename(y = median) %>%
  mutate(rel_year = rel_year + 3) %>%
  left_join(ind)
fit
```

## Trajectories

```{r traj_ba}
#| message: false
#| warning: false
#| fig-cap: "Basal area jointly inferred trajectories for all sites."
#| fig-height: 10
#| fig-width: 10
filter(trajs, variable == "ba") %>% 
  ggplot(aes(rel_year, y)) +
  geom_line(aes(group = paste(site, plotnum), col = as.character(plotnum))) +
  geom_point(aes(group = paste(site, plotnum), col = as.character(plotnum)),
      data = data %>% filter(variable == "ba"), alpha = .5
  ) +
  facet_wrap(~site, scales = "free") +
  theme_bw() +
  xlab("") + ylab("") +
  theme(legend.position = "bottom") +
  scale_color_discrete(guide = "none")
```

```{r traj_div}
#| message: false
#| warning: false
#| fig-cap: "Genus diversity jointly inferred trajectories for all sites."
#| fig-height: 10
#| fig-width: 10
filter(trajs, variable == "diversity_q0_sp") %>% 
  ggplot(aes(rel_year, y)) +
  geom_line(aes(group = paste(site, plotnum), col = as.character(plotnum))) +
  geom_point(aes(group = paste(site, plotnum), col = as.character(plotnum)),
      data = data %>% filter(variable == "diversity_q0_sp"), alpha = .5
  ) +
  facet_wrap(~site, scales = "free") +
  theme_bw() +
  xlab("") + ylab("") +
  theme(legend.position = "bottom") +
  scale_color_discrete(guide = "none")
```

## Disturbance

```{r eval_phi}
#| message: false
#| warning: false
#| fig-cap: "Evaluation of inferred disturbance intensity against observed with pre-logging inventories."
dist_obs <- data %>% 
  filter(variable == "ba") %>% 
  group_by(site, plot) %>%
  summarise(ba_post = min(y, na.rm = TRUE)) %>% 
  left_join(read_tsv("../modelling/data/derived_data/data_equ.tsv",
                     col_types = cols()) %>%
              filter(variable == "ba") %>% 
              filter(rel_year <= 0) %>%
              group_by(site, plot) %>%
              summarise(ba_pre = median(value, na.rm = TRUE))) %>% 
    na.omit() %>% 
  mutate(dist_obs = (ba_pre - ba_post) / ba_pre * 100) %>%
  select(site, plot, dist_obs) %>%
  filter(dist_obs > 0)
fit$summary("phi_ba_p") %>% 
  separate(variable, c("X1", "X2", "X3", "plotnum"), convert = TRUE) %>% 
  select(-X1, -X2, -X3) %>% 
  left_join(ind) %>% 
  left_join(dist_obs) %>%
  na.omit() %>%
  ggplot(aes((1-median)*100, dist_obs)) +
  geom_abline(col = "darkgrey") +
  geom_segment(aes(x = median - sd, xend = median + sd)) +
  geom_segment(aes(x = q5, xend = q95), size = .1) +
  geom_point() +
  facet_wrap(~site) +
  theme_bw() +
  ggpubr::stat_cor(size = 3) +
  xlab(expression(phi[BA] ~ "inferred [ % lost ]")) +
  ylab(expression(dist[BA] ~ "observed [ % lost ]")) +
  theme(panel.spacing = unit(0, "lines")) +
  xlim(0, 100) + ylim(0, 100)
```

## IDH - H1

```{r}
#| message: false
#| warning: false
pars <- ind %>% 
  left_join(fit$summary("delta_p") %>% 
  separate(variable, c("parameter", "p", "plotnum"), convert = TRUE) %>% 
              select(-p)) %>% 
  left_join(fit$summary("phi_ba_p") %>% 
              mutate(variable = gsub("phi_ba_p", "phiba_p", variable)) %>% 
              separate(variable, c("parameter", "p", "plotnum"), convert = TRUE) %>% 
              select(-p), by = "plotnum")

pars %>% 
  ggplot(aes(median.x*100, (1-median.y)*100)) +
  geom_vline(xintercept = 0) +
  geom_segment(aes(x = (median.x - sd.x)*100,
                   xend = (median.x + sd.x)*100), col = "darkgrey") +
  geom_segment(aes(x = q5.x*100, xend = q95.x*100), size = .1, col = "darkgrey") +
  geom_segment(aes(y = (1-(median.y - sd.y))*100,
                   yend = (1-(median.y + sd.y))*100), col = "darkgrey") +
    geom_point() +
  facet_wrap(~ site, scales = "free") +
  theme_bw() +
  ylab(expression(phi[BA] ~ "[ % lost ]")) +
  xlab(expression(delta[Diversity] ~ "[ % ]"))
```

```{r}
#| message: false
#| warning: false
pars %>% 
  ggplot(aes(median.x)) +
  geom_histogram(fill = "lightgrey", col = "black") +
  geom_vline(xintercept = 0) +
  theme_bw() +
  facet_wrap(~ site, scales = "free_y") +
  xlab(expression(delta[Diversity] ~ "[ % ]"))
```

```{r}
#| message: false
#| warning: false
pars %>% 
  ggplot(aes(median.x)) +
  geom_histogram(aes(fill = site), col = "black") +
  geom_vline(xintercept = 0) +
  theme_bw() +
  xlab(expression(delta[Diversity] ~ "[ % ]"))
```

```{r}
#| message: false
#| warning: false
pars %>% 
  filter(!grepl("Tapajos", site)) %>% 
  ggplot(aes(median.x)) +
  geom_histogram(aes(fill = site), col = "black") +
  geom_vline(xintercept = 0) +
  theme_bw() +
  xlab(expression(delta[Diversity] ~ "[ % ]"))
```

## IDH - H2

```{r intervals}
#| message: false
#| warning: false
#| fig-cap: "Posterior of the parameter gamma representing basal are disturbance intensity effect on genus diversity short term increase"
fit$draws(c("gamma_s")) %>% 
  mcmc_intervals() +
  scale_y_discrete(labels = unique(ind$site)) +
  scale_x_reverse(expression(gamma~"["~"%"~"%"^{-1}~"]"), lim = c(4,-4)) 
```

```{r relation}
#| message: false
#| warning: false
#| fig-cap: "Inferred relationship between disturbance intensity and diversity short term increase."
pars <- ind %>% 
  left_join(fit$summary(c("delta0_s"), "median") %>% 
              separate(variable, c("parameter", "s", "sitenum"), convert = TRUE) %>% 
              select(-s) %>% 
              pivot_wider(names_from = parameter, values_from = median)) %>% 
  left_join(fit$summary("gamma_s") %>% 
              separate(variable, c("parameter", "s", "sitenum"), convert = TRUE) %>% 
              select(-s) %>% 
              pivot_wider(names_from = parameter, values_from = median)) %>% 
  left_join(fit$summary(c("phi_ba_p", "delta_p"), "median") %>% 
              mutate(variable = gsub("phi_ba_p", "phiba_p", variable)) %>% 
              separate(variable, c("parameter", "p", "plotnum"), convert = TRUE) %>% 
              select(-p) %>% 
              pivot_wider(names_from = parameter, values_from = median))
pars %>% 
  ggplot(aes((1-phiba), delta)) +
  facet_wrap(~ site) +
  geom_abline(aes(slope = -mean, 
                  intercept = mean+delta0, group = site), 
              data = pars) +
    geom_abline(aes(slope = -mean-sd, 
                  intercept = mean-sd+delta0, group = site), 
              data = pars, linetype = "dashed") +
  geom_abline(aes(slope = -mean+sd, 
                  intercept = mean+sd+delta0, group = site), 
              data = pars, linetype = "dashed") +
  geom_point() +
  theme_bw() +
  xlab(expression(phi[BA] ~ "[ % lost ]")) +
  ylab(expression(delta[Diversity] ~ "[ % ]")) +
  theme(panel.spacing = unit(0, "lines")) +
  scale_x_continuous(labels = ~.*100) +
  scale_y_continuous(labels = ~.*100)
```

```{r}
#| message: false
#| warning: false
fit$summary(c("gamma_s")) %>% 
  ggplot(aes(median)) +
  geom_histogram(fill = "lightgrey", col = "black", binwidth = 0.2) +
  geom_vline(xintercept = 0) +
  theme_bw() +
  scale_x_reverse(expression(gamma~"["~"%"~"%"^{-1}~"]"))
```
