```{r set}
#| message: false
#| include: false
library(tidyverse)
```

# Joint all {.unnumbered}

A comparison of the different joint modelling.

```{r}
#| message: false
#| warning: false
#| fig-height: 6
#| fig-width: 9
pars_gen1 <- read_tsv("chains/joint-diversity_q1_gen-parameters.tsv")
pars_gen0 <- read_tsv("chains/joint-diversity_q0_gen-parameters.tsv")
pars_sp1 <- read_tsv("chains/joint-diversity_q1_sp-parameters.tsv")
pars_sp0 <- read_tsv("chains/joint-diversity_q0_sp-parameters.tsv")

delta_subfig <- function(pars)
    pars_gen1 %>%
    filter(variable == "delta") %>%
    left_join(filter(pars, variable == "delta") %>%
      select(site, plot, median, sd, q5, q95) %>%
      rename(
        median_new = median, sd_new = sd,
        q5_new = q5, q95_new = q95
      )) %>%
    filter(!is.na(median_new)) %>%
    ggplot(aes(median, median_new)) +
    geom_hline(yintercept = 0, col = "grey") +
    geom_vline(xintercept = 0, col = "grey") +
    geom_point() +
    geom_segment(aes(x = median - sd, 
                     xend = median + sd)) +
    geom_segment(aes(x = q5, xend = q95), size = .1) +
    geom_segment(aes(y = (median_new - sd_new), 
                     yend = (median_new + sd_new))) +
    geom_segment(aes(y = q5_new, yend = q95_new), size = .1) +
    theme_bw() +
    geom_abline() +
    ggpubr::stat_cor(aes(group = NA)) +
    xlab(expression(delta[~~"genus order 1"] ~ "[ % ]")) +
    scale_x_continuous(labels = ~ . * 100) +
    scale_y_continuous(labels = ~ . * 100) +
    xlim(-.5, .5) +
    ylim(-.5, .5) +
    coord_equal()

gamma_subfig <- function(pars)
  pars_gen1 %>%
  filter(variable == "gamma") %>%
    left_join(filter(pars, variable == "gamma") %>%
      select(site, median, sd, q5, q95) %>%
      rename(
        median_new = median, sd_new = sd,
        q5_new = q5, q95_new = q95
      )) %>%
    filter(!is.na(median_new)) %>%
    mutate(median = -median, q5 = -q5, q95 = -q95) %>%
    mutate(median_new = -median_new, 
           q5_new = -q5_new, q95_new = -q95_new) %>%
    ggplot(aes(median, median_new)) +
    geom_hline(yintercept = 0, col = "grey") +
    geom_vline(xintercept = 0, col = "grey") +
    geom_point() +
    geom_segment(aes(x = median - sd, xend = median + sd)) +
    geom_segment(aes(x = q5, xend = q95), size = .1) +
    geom_segment(aes(y = median_new - sd_new, yend = median_new + sd_new)) +
    geom_segment(aes(y = q5_new, yend = q95_new), size = .1) +
    theme_bw() +
    geom_abline() +
    ggpubr::stat_cor() +
    xlab(expression(gamma[~~"genus order 1"] ~ "[" ~ "%"[~Diversity] ~ "%"[~Basal ~ Area] ~ ""^{
      -1
    } ~ "]")) +
    scale_x_continuous(labels = ~ . * 100) +
    scale_y_continuous(labels = ~ . * 100) +
    xlim(-1, 1) +
    ylim(-1, 1) +
    coord_equal()

g <- cowplot::plot_grid(
  delta_subfig(pars_gen0) + ylab(delta[~~"genus order 0"] ~ "[ % ]"),
  delta_subfig(pars_sp0) + ylab(delta[~~"species order 0"] ~ "[ % ]"),
  delta_subfig(pars_sp1) + ylab(delta[~~"species order 1"] ~ "[ % ]"),
  gamma_subfig(pars_gen0) + ylab(expression(gamma[~~"genus order 0"] ~ "[" ~ "%"[~Diversity] ~ "%"[~Basal ~ Area] ~ ""^{
      -1
    } ~ "]")),
  gamma_subfig(pars_sp0) + ylab(expression(gamma[~~"species order 0"] ~ "[" ~ "%"[~Diversity] ~ "%"[~Basal ~ Area] ~ ""^{
      -1
    } ~ "]")),
  gamma_subfig(pars_sp1) + ylab(expression(gamma[~~"species order 1"] ~ "[" ~ "%"[~Diversity] ~ "%"[~Basal ~ Area] ~ ""^{
      -1
    } ~ "]")),
  nrow = 2)

cowplot::save_plot("figures/figS6.png", 
                   plot = g, 
                   base_width = 9, 
                   base_height = 6, 
                   dpi = 300,
                   bg = "white")

g
```
