```{r set}
#| message: false
#| include: false
library(tidyverse)
library(cmdstanr)
library(bayesplot)
```

# Dist plot sp 0 {.unnumbered}

```{r}
#| eval: false
dif <- 0
var <- "diversity_q0_sp"
model <- cmdstan_model("models/disturbance_plot.stan")
basename <- paste0("distplot-", var)
out_dir <- file.path("chains", basename)

data <- read_tsv("../modelling/data/derived_data/data.tsv",
    col_types = cols()
  ) %>%
  select(-y) %>% 
  filter(treatment == "logged") %>% 
  filter(variable %in% c("ba", var)) %>% 
  na.omit() %>%
  filter(!(site %in% c(
      "Manare", "Montagne Tortue", "Nelliyampathy",
      "Uppangala", "BAFOG", "Sao Nicolau",
      "Kabo", "Mil", "Corinto",
      "Peixoto", "Iwokrama", "Antimary", "Peteco"
  ))) %>% 
  select(-sitenum) %>% 
  pivot_wider(names_from = variable, values_from = value)
data_u <- filter(data, rel_year < 0)
data_r <- data_u %>% 
  select(site, plot) %>% 
  unique() %>% 
  left_join(data) %>% 
  filter(rel_year > dif)
dist_obs <- data_r %>%
    group_by(site, plot) %>%
    summarise(ba_post = min(ba, na.rm = TRUE)) %>%
    left_join(data_u %>% 
      group_by(site, plot) %>%
      summarise(ba_pre = median(ba, na.rm = TRUE))) %>%
    mutate(dist_obs = (ba_pre - ba_post) / ba_pre) %>%
    select(site, plot, dist_obs) %>% 
  mutate(dist_obs = ifelse(dist_obs < 0, 0, dist_obs))
ind <- data_r %>%
    select(site, plot) %>%
    unique() %>% 
  left_join(dist_obs) %>% 
    mutate(sitenum = as.numeric(as.factor(site))) %>%
    mutate(plotnum = as.numeric(as.factor(paste(site, plot))))
data_u <- ind %>% 
  left_join(data_u)
data_r <- ind %>% 
  left_join(data_r)
mdata <- list(
  n = nrow(data_r),
  s = max(data_r$sitenum),
  p = max(data_r$plotnum),
  y = data_r$diversity_q0_sp,
  t = data_r$rel_year-dif,
  site = data_r$sitenum,
  plot = data_r$plotnum,
  site_plot = ind$sitenum,
  n_u = nrow(data_u),
  y_u = data_u$diversity_q0_sp,
  plot_u = data_u$plotnum,
  dist_p = ind$dist_obs
)

fit <- model$sample(
    mdata,
    chains = 4,
    parallel_chains = 4,
    save_warmup = FALSE,
    refresh = 100,
    output_dir = out_dir
)
```

```{r}
#| message: false
#| warning: false
dif <- 0
var <- "diversity_q0_sp"
basename <- paste0("distplot-", var)
out_dir <- file.path("chains", basename)
data <- read_tsv("../modelling/data/derived_data/data.tsv",
    col_types = cols()
  ) %>%
  select(-y) %>% 
  filter(treatment == "logged") %>% 
  filter(variable %in% c("ba", var)) %>% 
  na.omit() %>%
  filter(!(site %in% c(
      "Manare", "Montagne Tortue", "Nelliyampathy",
      "Uppangala", "BAFOG", "Sao Nicolau",
      "Kabo", "Mil", "Corinto",
      "Peixoto", "Iwokrama", "Antimary", "Peteco"
  ))) %>% 
  select(-sitenum) %>% 
  pivot_wider(names_from = variable, values_from = value)
data_u <- filter(data, rel_year < 0)
data_r <- data_u %>% 
  select(site, plot) %>% 
  unique() %>% 
  left_join(data) %>% 
  filter(rel_year > dif)
dist_obs <- data_r %>%
    group_by(site, plot) %>%
    summarise(ba_post = min(ba, na.rm = TRUE)) %>%
    left_join(data_u %>% 
      group_by(site, plot) %>%
      summarise(ba_pre = median(ba, na.rm = TRUE))) %>%
    mutate(dist_obs = (ba_pre - ba_post) / ba_pre) %>%
    select(site, plot, dist_obs) %>% 
  mutate(dist_obs = ifelse(dist_obs < 0, 0, dist_obs))
ind <- data_r %>%
    select(site, plot) %>%
    unique() %>% 
  left_join(dist_obs) %>% 
    mutate(sitenum = as.numeric(as.factor(site))) %>%
    mutate(plotnum = as.numeric(as.factor(paste(site, plot))))
data_u <- ind %>% 
  left_join(data_u)
data_r <- ind %>% 
  left_join(data_r)
fit <- as_cmdstan_fit(list.files(out_dir,
    full.names = TRUE
  ))
trajectories <- fit$summary("y_pred", "median") %>%
    separate(variable,
      c("variable", "pred", "rel_year", "plotnum"),
      convert = TRUE
    ) %>%
    select(-pred) %>%
    mutate(variable = recode(variable, "y" = var)) %>%
    rename(y = median) %>%
    mutate(rel_year = rel_year +dif) %>%
    left_join(ind)
pars_p <- fit$summary(c("delta_p")) %>%
    separate(variable, c("variable", "p", "plotnum"), convert = TRUE) %>%
    select(-p) %>%
    left_join(ind)
```

```{r}
#| message: false
#| warning: false
#| fig-cap: "Caption."
#| fig-height: 10
#| fig-width: 10
trajectories %>%
  filter(variable == "diversity_q0_sp") %>%
  ggplot() +
  geom_line(aes(rel_year, y, col = paste(site, plot))) +
  geom_point(
    data = data %>% 
      filter(paste(site, plot) %in% paste(ind$site, ind$plot)) %>% 
      mutate(rel_year=rel_year),
    aes(rel_year, diversity_q0_sp, col = paste(site, plot)),
    alpha = .5
  ) +
  facet_wrap(~ site, scales = "free_y", nrow = 6) +
  theme_bw() +
  xlab("") +
  ylab("") +
  geom_vline(xintercept = 0) +
    scale_color_manual(guide = "none", 
                     values = rainbow(max(ind$plotnum), 
                                      s=.6, v=.9)[sample(1:max(ind$plotnum),
                                                         max(ind$plotnum))])
```

```{r}
#| message: false
#| warning: false
 ggplot(pars_p, aes(dist_obs, median)) +
   geom_point() +
   theme_bw() +
   facet_wrap(~ site, scales = "free") +
   geom_smooth(method = "lm", formula = y ~ poly(x, degree = 2))
```

```{r}
pars_p %>% 
  filter(site != "Pad Limo") %>% 
  ggplot(aes(dist_obs, median)) +
  geom_point(aes(col = site)) +
  theme_bw() +
  geom_smooth(method = "lm", formula = y ~ 0 + I(x^2) + x) +
  ggpubr::stat_cor() +
  scale_color_discrete() +
  theme(legend.position = "bottom")
```

```{r}
# library(segmented)

```

```{r}
pars_p %>% 
  filter(site %in% c("Paracou", "Mbaiki", "SUAS")) %>% 
  ggplot(aes(dist_obs, median)) +
   geom_point(aes(col = site)) +
   theme_bw() +
   geom_smooth(method = "lm") +
   ggpubr::stat_cor() +
  scale_color_discrete()
```

```{r}
#| message: false
#| warning: false
pars_gen1 <- read_tsv("chains/joint-diversity_q0_sp-parameters.tsv")
pars_p %>%
    left_join(filter(pars_gen1, variable == "delta") %>%
      select(site, plot, median, sd, q5, q95) %>%
      rename(
        median_new = median, sd_new = sd,
        q5_new = q5, q95_new = q95
      )) %>%
    filter(!is.na(median_new)) %>%
    ggplot(aes(median, median_new)) +
    geom_hline(yintercept = 0, col = "grey") +
    geom_vline(xintercept = 0, col = "grey") +
    geom_point() +
    geom_segment(aes(x = median - sd, 
                     xend = median + sd)) +
    geom_segment(aes(x = q5, xend = q95), size = .1) +
    geom_segment(aes(y = (median_new - sd_new), 
                     yend = (median_new + sd_new))) +
    geom_segment(aes(y = q5_new, yend = q95_new), size = .1) +
    theme_bw() +
    geom_abline() +
    ggpubr::stat_cor(aes(group = NA)) +
    xlab(expression(delta[~~"previous~model"] ~ "[ % ]")) +
    xlab(expression(delta[~~"new~model"] ~ "[ % ]")) +
    scale_x_continuous(labels = ~ . * 100) +
    scale_y_continuous(labels = ~ . * 100) +
    xlim(-.5, .5) +
    ylim(-.5, .5) +
    coord_equal()
```
