# Treatment - $\gamma$ {.unnumbered}

```{r set}
#| message: false
#| include: false
library(tidyverse)
```

-   area
-   \# censuses
-   Duration: first & last censuses
-   Censuse frequency
-   Country, continent, geography
-   Determination level
-   Co-variables

```{r data}
#| message: false
#| warning: false
data <- read_tsv("../modelling/data/derived_data/data_rec.tsv",
  col_types = cols()
) %>%
  select(-y) %>%
  filter(variable %in% c("ba", "diversity_q1_gen")) %>%
  select(-sitenum, -plotnum) %>%
  pivot_wider(names_from = variable, values_from = value) %>%
  na.omit() %>%
  filter(!(site %in% c(
    "Manare", "Montagne Tortue", "Nelliyampathy",
    "Uppangala", "BAFOG", "Sao Nicolau",
    "Kabo", "Mil", "Corinto",
    "Peixoto", "Iwokrama", "Antimary", "Peteco"
  ))) %>%
  mutate(sitenum = as.numeric(as.factor(site))) %>%
  mutate(plotnum = as.numeric(as.factor(paste(site, plot)))) %>%
  arrange(sitenum, plotnum, rel_year) %>%
  gather(
    variable, y, -plot, -year, -site, -treatment, -harvest_year,
    -longitude, -harvest_year_min, -rel_year, -sitenum, -plotnum
  )
metrics <- data %>%
  filter(variable == "diversity_q1_gen") %>%
  group_by(site, plot) %>%
  summarise(
    censuses = n(),
    duration = max(year) - mean(year)
  ) %>%
  mutate(frequency = duration / censuses) %>%
  group_by(site) %>%
  summarise(
    censuses = median(censuses),
    duration = median(duration),
    frequency = median(frequency)
  )
area <- data %>%
  filter(variable == "area") %>%
  select(site, plot, y) %>%
  unique() %>%
  group_by(site) %>%
  summarise(area = median(y))
env <- read_tsv("../modelling/outputs/parameters.tsv") %>%
  select(
    site, region, et, cwd, pr, tmax, vpd, soil,
    dsl, dsi, bdod, cec, cfvo, clay, sand, silt, nitrogen,
    phh2o, soc, ocd, FDiv_s, SLA_cwm_ba_s, WD_cwm_ba_s,
    diversity_q1_gen_s, gini_s
  ) %>%
  na.omit() %>%
  unique()
pad_sites <- c(
  "Pad Limo 2 Barracos", "Pad Limo Chico Bocao", "Pad Limo Cumaru",
  "Pad Limo Jatoba", "Pad Limo Pocao", "Pad Limo STCP"
)
undet <- read_csv("../modelling/data/raw_data/aggregated_data_v9.csv") %>%
  rename_all(tolower) %>%
  filter(variable == "p_undet_gen") %>%
  group_by(site) %>%
  mutate(site = ifelse(site %in% pad_sites, "Pad Limo", site)) %>%
  summarise(p_undet_genus = median(value))
dbh_min <- read_csv("../modelling/data/raw_data/aggregated_data_v9.csv") %>%
  rename_all(tolower) %>%
  filter(variable == "dbh_min") %>%
  group_by(site) %>%
  mutate(site = ifelse(site %in% pad_sites, "Pad Limo", site)) %>%
  summarise(dbh_min = median(value))
parameters <- read_tsv("chains/joint-diversity_q1_gen-parameters.tsv") %>%
  left_join(area) %>%
  left_join(metrics) %>%
  left_join(env) %>%
  left_join(undet) %>%
  left_join(dbh_min)
```

```{r area}
#| message: false
#| warning: false
#| fig-cap: "Area effect."
filter(parameters, variable == "gamma") %>%
  ggplot(aes(median, reorder(site, median), col = area)) +
  geom_vline(xintercept = 0, col = "darkgrey") +
  geom_segment(aes(
    x = (median - sd),
    xend = (median + sd)
  )) +
  geom_segment(aes(x = q5, xend = q95), size = .1) +
  geom_point() +
  geom_text(aes(label = paste(round(area, 1), "ha")), nudge_y = .5, size = 2) +
  theme_bw() +
  scale_x_reverse(expression(gamma ~ "[" ~ "%" ~ "%"^{
    -1
  } ~ "]")) +
  ylab("") +
  scale_color_viridis_c(guide = "none") +
  ggtitle("Area [ ha ]")
```

```{r censuses}
#| message: false
#| warning: false
#| fig-cap: "Number of censuses effect."
filter(parameters, variable == "gamma") %>%
  ggplot(aes(median, reorder(site, median), col = censuses)) +
  geom_vline(xintercept = 0, col = "darkgrey") +
  geom_segment(aes(
    x = (median - sd),
    xend = (median + sd)
  )) +
  geom_segment(aes(x = q5, xend = q95), size = .1) +
  geom_point() +
  geom_text(aes(label = censuses), nudge_y = .5, size = 2) +
  theme_bw() +
  scale_x_reverse(expression(gamma ~ "[" ~ "%" ~ "%"^{
    -1
  } ~ "]")) +
  ylab("") +
  scale_color_viridis_c(guide = "none") +
  ggtitle("Censuses [ # ]")
```

```{r duration}
#| message: false
#| warning: false
#| fig-cap: "Duration effect."
filter(parameters, variable == "gamma") %>%
  ggplot(aes(median, reorder(site, median), col = duration)) +
  geom_vline(xintercept = 0, col = "darkgrey") +
  geom_segment(aes(
    x = (median - sd),
    xend = (median + sd)
  )) +
  geom_segment(aes(x = q5, xend = q95), size = .1) +
  geom_point() +
  geom_text(aes(label = round(duration)), nudge_y = .5, size = 2) +
  theme_bw() +
  scale_x_reverse(expression(gamma ~ "[" ~ "%" ~ "%"^{
    -1
  } ~ "]")) +
  ylab("") +
  scale_color_viridis_c(guide = "none") +
  ggtitle("Duration [ yr ]")
```

```{r frequency}
#| message: false
#| warning: false
#| fig-cap: "Frequency effect."
filter(parameters, variable == "gamma") %>%
  ggplot(aes(median, reorder(site, median), col = frequency)) +
  geom_vline(xintercept = 0, col = "darkgrey") +
  geom_segment(aes(
    x = (median - sd),
    xend = (median + sd)
  )) +
  geom_segment(aes(x = q5, xend = q95), size = .1) +
  geom_point() +
  geom_text(aes(label = round(frequency)), nudge_y = .5, size = 2) +
  theme_bw() +
  scale_x_reverse(expression(gamma ~ "[" ~ "%" ~ "%"^{
    -1
  } ~ "]")) +
  ylab("") +
  scale_color_viridis_c(guide = "none") +
  ggtitle("Frequency [ # / yr ]")
```

```{r undet}
#| message: false
#| warning: false
#| fig-cap: "Genus undetermined."
continent <- read_tsv("../modelling/outputs/parameters.tsv") %>%
  select(site, region) %>%
  unique() %>%
  na.omit() %>%
  mutate(continent = paste0(str_sub(region, 1, 2), "."))
g <- filter(parameters, variable == "gamma") %>%
  mutate(median = -median, q5 = -q5, q95 = -q95) %>%
  left_join(continent) %>%
  mutate(name = paste(continent, site)) %>%
  ggplot(aes(median, reorder(name, -median), col = p_undet_genus)) +
  geom_vline(xintercept = 0, col = "darkgrey") +
  geom_segment(aes(
    x = (median - sd),
    xend = (median + sd)
  )) +
  geom_segment(aes(x = q5, xend = q95), size = .1) +
  geom_point() +
  geom_text(aes(label = paste0(round(p_undet_genus * 100), "%")), 
            nudge_y = .5, size = 2) +
  theme_bw() +
  xlab(expression(gamma ~ "[" ~ "%"[~Diversity] ~ "%"[~Basal ~ Area] ~ ""^{
    -1
  } ~ "]")) +
  ylab("") +
  scale_color_viridis_c(guide = "none") +
  ggtitle("Genus undetermined [ % ]")
ggsave("figures/figS7.png", width = 6, height = 4, g, dpi = 300, bg = "white")
g
```

```{r dbh_min}
#| message: false
#| warning: false
#| fig-cap: "Minimum dbh effect."
filter(parameters, variable == "gamma") %>%
  ggplot(aes(median, reorder(site, median), col = dbh_min)) +
  geom_vline(xintercept = 0, col = "darkgrey") +
  geom_segment(aes(
    x = (median - sd),
    xend = (median + sd)
  )) +
  geom_segment(aes(x = q5, xend = q95), size = .1) +
  geom_point() +
  geom_text(aes(label = round(dbh_min)), nudge_y = .5, size = 2) +
  theme_bw() +
  scale_x_reverse(expression(gamma ~ "[" ~ "%" ~ "%"^{
    -1
  } ~ "]")) +
  ylab("") +
  scale_color_viridis_c(guide = "none") +
  ggtitle("Minimum dbh [ cm ]")
```

```{r region}
#| message: false
#| warning: false
#| fig-cap: "Region effect."
filter(parameters, variable == "gamma") %>%
  ggplot(aes(median, reorder(site, median), col = region)) +
  geom_vline(xintercept = 0, col = "darkgrey") +
  geom_segment(aes(
    x = (median - sd),
    xend = (median + sd)
  )) +
  geom_segment(aes(x = q5, xend = q95), size = .1) +
  geom_point() +
  geom_text(aes(label = region), nudge_y = .5, size = 2) +
  theme_bw() +
  scale_x_reverse(expression(gamma ~ "[" ~ "%" ~ "%"^{
    -1
  } ~ "]")) +
  ylab("") +
  scale_color_viridis_d(guide = "none") +
  ggtitle("Region")
```

```{r lm}
lm(-median ~ area + censuses + duration + frequency + region + p_undet_genus,
  data = filter(parameters, variable == "gamma")
) %>%
  sjPlot::tab_model()
```

```{r}
lm(
  -median ~ cwd + pr + tmax + bdod + clay + sand +
    FDiv_s + SLA_cwm_ba_s + WD_cwm_ba_s + diversity_q1_gen_s + gini_s,
  data = filter(parameters, variable == "gamma")
) %>%
  sjPlot::tab_model()
```

```{r cwd}
#| message: false
#| warning: false
#| fig-cap: "Frequency effect."
filter(parameters, variable == "gamma") %>%
  ggplot(aes(median, reorder(site, median), col = cwd)) +
  geom_vline(xintercept = 0, col = "darkgrey") +
  geom_segment(aes(
    x = (median - sd),
    xend = (median + sd)
  )) +
  geom_segment(aes(x = q5, xend = q95), size = .1) +
  geom_point() +
  geom_text(aes(label = round(cwd)), nudge_y = .5, size = 2) +
  theme_bw() +
  scale_x_reverse(expression(gamma ~ "[" ~ "%" ~ "%"^{
    -1
  } ~ "]")) +
  ylab("") +
  scale_color_viridis_c(guide = "none", direction = -1) +
  ggtitle("CWD [ mm ]")
```
