# $\delta~et~\gamma$ {.unnumbered}

```{r set}
#| message: false
#| include: false
library(tidyverse)
library(scales)
```

-   mean diversity of undisturbed
-   mean abundance of undisturbed

## Diversity

```{r }
#| message: false
#| warning: false
data <- read_tsv("../modelling/data/derived_data/data_equ.tsv",
  col_types = cols()
) %>%
  select(-y) %>%
  filter(variable %in% c("ba", "diversity_q1_gen")) %>%
  select(-sitenum, -plotnum) %>%
  pivot_wider(names_from = variable, values_from = value) %>%
  na.omit() %>%
  filter(!(site %in% c(
    "Manare", "Montagne Tortue", "Nelliyampathy",
    "Uppangala", "BAFOG", "Sao Nicolau",
    "Kabo", "Mil", "Corinto",
    "Peixoto", "Iwokrama", "Antimary", "Peteco"
  ))) %>% 
  select(site, plot, ba, diversity_q1_gen) %>% 
  group_by(site, plot) %>% 
  summarise_all(mean)
parameters <- read_tsv("chains/joint-diversity_q1_gen-parameters.tsv") %>%
  left_join(data)
```

```{r}
#| message: false
#| warning: false
filter(parameters, variable == "delta") %>%
  ggplot(aes(mean > 0, diversity_q1_gen,)) +
  geom_boxplot() +
  theme_bw() +
  ggpubr::stat_compare_means() +
  facet_wrap(~ site)
```

```{r}
#| message: false
#| warning: false
filter(parameters, variable == "delta") %>%
  ggplot(aes(diversity_q1_gen, mean, col = ba)) +
  geom_segment(aes(
    y = (median - sd),
    yend = (median + sd)
  )) +
  geom_segment(aes(y = q5, yend = q95), size = .1) +
  geom_point() +
  theme_bw() +
  ggpubr::stat_cor()  +
  scale_color_viridis_c("Basal area before logging") +
  ylab(expression(delta[Diversity] ~ "[ % ]")) +
  xlab("Genus diversity before logging") +
  theme(legend.position = "bottom")
```

```{r}
#| message: false
#| warning: false
filter(parameters, variable == "delta") %>%
  ggplot(aes(ba, mean, col = diversity_q1_gen)) +
  geom_segment(aes(
    y = (median - sd),
    yend = (median + sd)
  )) +
  geom_segment(aes(y = q5, yend = q95), size = .1) +
  geom_point() +
  theme_bw() +
  ggpubr::stat_cor()  +
  scale_color_viridis_c("Genus diversity before logging") +
  ylab(expression(delta[Diversity] ~ "[ % ]")) +
  xlab("Basal area before logging") +
  theme(legend.position = "bottom")
```

## Richness

```{r }
#| message: false
#| warning: false
data <- read_tsv("../modelling/data/derived_data/data_equ.tsv",
  col_types = cols()
) %>%
  select(-y) %>%
  filter(variable %in% c("ba", "diversity_q0_gen")) %>%
  select(-sitenum, -plotnum) %>%
  pivot_wider(names_from = variable, values_from = value) %>%
  na.omit() %>%
  filter(!(site %in% c(
    "Manare", "Montagne Tortue", "Nelliyampathy",
    "Uppangala", "BAFOG", "Sao Nicolau",
    "Kabo", "Mil", "Corinto",
    "Peixoto", "Iwokrama", "Antimary", "Peteco"
  ))) %>% 
  select(site, plot, ba, diversity_q0_gen) %>% 
  group_by(site, plot) %>% 
  summarise_all(mean)
parameters <- read_tsv("chains/joint-diversity_q0_gen-parameters.tsv") %>%
  left_join(data)
```

```{r}
#| message: false
#| warning: false
filter(parameters, variable == "delta") %>%
  ggplot(aes(mean > 0, diversity_q0_gen,)) +
  geom_boxplot() +
  theme_bw() +
  ggpubr::stat_compare_means() +
  facet_wrap(~ site)
```

```{r}
#| message: false
#| warning: false
filter(parameters, variable == "delta") %>%
  ggplot(aes(mean > 0, diversity_q0_gen,)) +
  geom_boxplot() +
  theme_bw() +
  ggpubr::stat_compare_means() +
  facet_wrap(~ site)
```

```{r}
filter(parameters, variable == "delta") %>%
  ggplot(aes(diversity_q0_gen, mean, col = ba)) +
  geom_segment(aes(
    y = (median - sd),
    yend = (median + sd)
  )) +
  geom_segment(aes(y = q5, yend = q95), size = .1) +
  geom_point() +
  theme_bw() +
  ggpubr::stat_cor()  +
  scale_color_viridis_c("Basal area before logging") +
  ylab(expression(delta[Diversity] ~ "[ % ]")) +
  xlab("Genus diversity before logging") +
  theme(legend.position = "bottom")
```

```{r}
#| message: false
#| warning: false
filter(parameters, variable == "delta") %>%
  ggplot(aes(ba, mean, col = diversity_q0_gen)) +
  geom_segment(aes(
    y = (median - sd),
    yend = (median + sd)
  )) +
  geom_segment(aes(y = q5, yend = q95), size = .1) +
  geom_point() +
  theme_bw() +
  ggpubr::stat_cor()  +
  scale_color_viridis_c("Genus diversity before logging") +
  ylab(expression(delta[Diversity] ~ "[ % ]")) +
  xlab("Basal area before logging") +
  theme(legend.position = "bottom")
```
