project:
  type: book
  output-dir: docs

book:
  title: "Diversity"
  date: last-modified
  chapters:
    - index.qmd
    - 01_framework.qmd
    - 10_data.qmd
    - 20_model.qmd
    - 21_disturbance.qmd
    - 22_species.qmd
    - 23_determinants.qmd
  appendices:
    - 96_literature.qmd
    - 97_meeting.qmd
    - 99_references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    code-fold: true
    number-depth: -1

editor: visual
