project:
  type: book
  output-dir: docs

book:
  title: "Diversity"
  date: last-modified
  chapters:
    - index.qmd
    - 01_framework.qmd
    - 10_data.qmd
    - part: 20_fits.qmd
      chapters:
      - 21_jointgen.qmd
      - 22_distgen.qmd
      - 23_jointsp.qmd
      - 24_jointgen0.qmd
      - 25_jointsp0.qmd
      - 26_jointgen_nointercept.qmd
      - 27_jointgen_quad.qmd
      - 28_jointall.qmd
      - 29_dist_plot.qmd
      - 29b_dist_plot0.qmd
    - part: 30_exploration.qmd
      chapters:
      - 31_maturity.qmd
      - 32_treatment.qmd
      - 33_treatment2.qmd
      - 34_treatment3.qmd
      - 35_tau.qmd
      - 36_deltagamma.qmd
  appendices:
    - 96_literature.qmd
    - 97_meeting.qmd
    - 99_references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    code-fold: true
    number-depth: -1

editor: visual
