project:
  type: book
  output-dir: docs

book:
  title: "Diversity"
  date: last-modified
  chapters:
    - index.qmd
    - 10_data.qmd
    - 20_model.qmd
    - 30_rarefied_richness.qmd
    - 31_raw_richness.qmd
    - 40_sensitivity.qmd
  appendices:
    - 97_meeting.qmd
    - 99_references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    code-fold: true
    number-depth: -1

editor: visual
